# Generated by Django 4.1.2 on 2023-01-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
    ]
