# Generated by Django 4.1.2 on 2023-01-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0002_auto_20230124_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('No_of_guests', models.SmallIntegerField(default=1)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(db_index=True, max_length=255)),
                ('Price', models.DecimalField(db_index=True, decimal_places=2, max_digits=6)),
                ('Inventory', models.SmallIntegerField(db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Menu Items',
            },
        ),
    ]
